version: '3.8'

services:
  solana-dapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi_solana_dapp
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
